#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cantarell-fonts
Version  : 0.0.25
Release  : 3
URL      : https://download.gnome.org/sources/cantarell-fonts/0.0/cantarell-fonts-0.0.25.tar.xz
Source0  : https://download.gnome.org/sources/cantarell-fonts/0.0/cantarell-fonts-0.0.25.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : OFL-1.1
Requires: cantarell-fonts-data
BuildRequires : sed

%description
==========================
This file provides detailed information on the Cantarell font
software. This information should be distributed along with the
Cantarell fonts and any derivative works.

%package data
Summary: data components for the cantarell-fonts package.
Group: Data

%description data
data components for the cantarell-fonts package.


%prep
%setup -q -n cantarell-fonts-0.0.25

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516656450
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1516656450
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fontconfig/conf.avail/31-cantarell.conf
/usr/share/fonts/cantarell/Cantarell-Bold.otf
/usr/share/fonts/cantarell/Cantarell-BoldOblique.otf
/usr/share/fonts/cantarell/Cantarell-Oblique.otf
/usr/share/fonts/cantarell/Cantarell-Regular.otf
