#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cantarell-fonts
Version  : 0.111
Release  : 6
URL      : https://download.gnome.org/sources/cantarell-fonts/0.111/cantarell-fonts-0.111.tar.xz
Source0  : https://download.gnome.org/sources/cantarell-fonts/0.111/cantarell-fonts-0.111.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : OFL-1.1
Requires: cantarell-fonts-data = %{version}-%{release}
Requires: cantarell-fonts-license = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson

%description
Cantarell
=========
This file provides detailed information on the Cantarell font software. This information should be distributed along with the Cantarell fonts and any derivative works.

%package data
Summary: data components for the cantarell-fonts package.
Group: Data

%description data
data components for the cantarell-fonts package.


%package license
Summary: license components for the cantarell-fonts package.
Group: Default

%description license
license components for the cantarell-fonts package.


%prep
%setup -q -n cantarell-fonts-0.111

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555546055
export LDFLAGS="${LDFLAGS} -fno-lto"
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain -Dbuildappstream=true  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/cantarell-fonts
cp COPYING %{buildroot}/usr/share/package-licenses/cantarell-fonts/COPYING
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fonts/cantarell/Cantarell-Bold.otf
/usr/share/fonts/cantarell/Cantarell-ExtraBold.otf
/usr/share/fonts/cantarell/Cantarell-Light.otf
/usr/share/fonts/cantarell/Cantarell-Regular.otf
/usr/share/fonts/cantarell/Cantarell-Thin.otf
/usr/share/metainfo/org.gnome.cantarell.metainfo.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cantarell-fonts/COPYING
